// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lomtec.Proxy.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RoleDtoODataValue
    {
        /// <summary>
        /// Initializes a new instance of the RoleDtoODataValue class.
        /// </summary>
        public RoleDtoODataValue()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RoleDtoODataValue class.
        /// </summary>
        public RoleDtoODataValue(RoleDto value = default(RoleDto))
        {
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public RoleDto Value { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Value != null)
            {
                Value.Validate();
            }
        }
    }
}
