// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lomtec.Proxy.Client {
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;
    using Models;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Net;
    using System.Net.Http;

    /// <summary>
    /// Lomtec.com Identity Lomtec.IDP.API. Use only for testing.
    /// Toto som pridal a...
    /// </summary>
    public partial class IdentityLomtecIDPAPI {
        public IdentityLomtecIDPAPI(HttpClient httpClient) : base(httpClient, true) {
            Initialize();
            BaseUri = httpClient.BaseAddress;
        }
    }
}
